# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20171210_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(),
        ),
    ]
