# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20171213_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_photo',
            field=models.DateField(null=True, verbose_name='Date de la photo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_video',
            field=models.DateField(null=True, verbose_name='Date de la vidéo'),
        ),
    ]
