# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20171217_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
