# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20171218_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date_video',
            field=models.DateField(null=True, verbose_name='Date de la vidéo'),
        ),
    ]
